// This script generated by Hifive UI Creator
// Hifive Games - Gokhan Yahya TORBA 2020

using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;

public class UIManager : MonoBehaviour
{
    private static UIManager _instance = null;
    public static UIManager Instance => _instance;

    private void Awake()
    {
        if (_instance != null && _instance != this)
        {
            Destroy(this.gameObject);
        }
        _instance = this;
    }

    

    private void Start()
    {
        if (UnityEngine.iOS.Device.generation.ToString().Contains("iPad"))
            {
            Debug.Log("iPad device detected! Canvas Scaler Match Size increased to 1f");
            CanvasScaler[] scalers = GetComponents<CanvasScaler>();
            foreach (CanvasScaler canvasScaler in scalers)
            {
                canvasScaler.matchWidthOrHeight = 1f;
            }
        }else
        {
            Debug.Log("iPad device not detected! Canvas Scaler Match Size set to default");
        }
    }

    
}
        